name: monangchampaneri
description: Monang Champaneri personal and portfolio.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_text_kit: ^4.2.2 #animation_text
  google_fonts: ^6.1.0 #font
  flutter_svg: ^2.0.9 #svg
  flutter_riverpod: ^2.4.10 #state management
  flutter_staggered_grid_view: ^0.7.0  #staggedGrid
  url_launcher: ^6.2.4 #URLauncher
  scroll_to_index: ^3.0.1 #scrollToIndex
  http: ^1.2.1 #httpclient
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  #flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/

  fonts:
    - family: sfmono
      fonts:
        - asset: fonts/sfmono.otf

        
